plugins { id 'com.android.application' }

android {
    namespace 'id.co.ppa.p5mfuel'
    compileSdk 35

    defaultConfig {
        applicationId 'id.co.ppa.p5mfuel'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
